seed: 42

test_only: false

data_module:
  _target_: tdgu.data.TWCmdGenGraphEventDataModule
  train_path: data/cmd_gen.0.2/train.json
  train_batch_size: 64
  train_num_worker: 4
  val_path: data/cmd_gen.0.2/valid.json
  val_batch_size: 1024
  val_num_worker: 4
  test_path: data/cmd_gen.0.2/test.json
  test_batch_size: 1024
  test_num_worker: 4
  word_vocab_path: vocabs/word_vocab.txt
  node_vocab_path: vocabs/node_vocab.txt
  relation_vocab_path: vocabs/relation_vocab.txt

model:
  _target_: tdgu.nn.graph_updater.TemporalDiscreteGraphUpdater
  hidden_dim: 64
  word_emb_dim: 300
  dgnn_gnn: TransformerConv
  dgnn_timestamp_enc_dim: 16
  dgnn_num_gnn_block: 1
  dgnn_num_gnn_head: 1
  text_encoder_num_blocks: 1
  text_encoder_num_conv_layers: 5
  text_encoder_kernel_size: 5
  text_encoder_num_heads: 1
  graph_event_decoder_event_type_emb_dim: 16
  graph_event_decoder_hidden_dim: 64
  graph_event_decoder_autoregressive_emb_dim: 128
  graph_event_decoder_key_query_dim: 16
  graph_event_decoder_num_dec_blocks: 1
  graph_event_decoder_dec_block_num_heads: 1
  max_decode_len: 100
  dropout: 0.0
  pretrained_word_embedding_path: embedding/crawl-300d-2M.vec

train:
  learning_rate: 5e-4

trainer:
  _target_: pytorch_lightning.Trainer

defaults:
  - _self_
  - trainer/logger: null
  - objs_with_same_label: null
