seed: 42

data:
  train_path: data/cmd_gen.0.2/train.json
  train_batch_size: 200
  val_path: data/cmd_gen.0.2/valid.json
  val_batch_size: 1
  test_path: data/cmd_gen.0.2/test.json
  test_batch_size: 1
  word_vocab_file: vocabs/word_vocab.txt
  node_vocab_file: vocabs/node_vocab.txt
  relation_vocab_file: vocabs/relation_vocab.txt

model:
  hidden_dim: 64
  max_num_nodes: 2400000
  max_num_edges: 2600000
  word_emb_dim: 300
  text_encoder_num_blocks: 1
  text_encoder_num_conv_layers: 5
  text_encoder_kernel_size: 5
  text_encoder_num_heads: 1
  graph_event_decoder_key_query_dim: 64
  max_decode_len: 100
  pretrained_word_embedding_path: embedding/crawl-300d-2M.vec

train:
  learning_rate: 1e-3

pl_trainer:
  reload_dataloaders_every_epoch: true
