seed: 42

data:
  train_path: data/cmd_gen.0.2/train.json
  train_batch_size: 32
  train_num_worker: 4
  val_path: data/cmd_gen.0.2/valid.json
  val_batch_size: 8
  val_num_worker: 4
  test_path: data/cmd_gen.0.2/test.json
  test_batch_size: 8
  test_num_worker: 4
  word_vocab_file: vocabs/word_vocab.txt
  node_vocab_file: vocabs/node_vocab.txt
  relation_vocab_file: vocabs/relation_vocab.txt

model:
  hidden_dim: 64
  max_num_nodes: 1000
  max_num_edges: 1000
  word_emb_dim: 300
  tgn_event_type_emb_dim: 64
  tgn_memory_dim: 64
  tgn_time_enc_dim: 64
  tgn_num_gnn_block: 6
  tgn_num_gnn_head: 1
  text_encoder_num_blocks: 1
  text_encoder_num_conv_layers: 5
  text_encoder_kernel_size: 5
  text_encoder_num_heads: 1
  graph_event_decoder_key_query_dim: 64
  max_decode_len: 100
  truncated_bptt_steps: 5
  log_k_triple_sets: 3
  pretrained_word_embedding_path: embedding/crawl-300d-2M.vec

train:
  learning_rate: 1e-4

trainer:
  _target_: pytorch_lightning.Trainer

defaults:
  - trainer/logger: null
