name: CI testing

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        python-version: [3.6, 3.7, 3.8]

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 35

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Github Actions: Run step on specific OS: https://stackoverflow.com/a/57948488/4521646
    # - name: Setup macOS
    #   if: runner.os == 'macOS'
    #   run: |
    #     brew install libomp  # https://github.com/pytorch/pytorch/issues/20030

    # https://github.com/actions/cache/blob/master/examples.md#multiple-oss-in-a-workflow
    - uses: actions/cache@v2
      name: Pip cache
      if: startsWith(runner.os, 'Linux')
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        sudo apt-get install -y graphviz graphviz-dev
        pip install torch-scatter torch-sparse torch-geometric -f https://data.pyg.org/whl/torch-1.10.0+cpu.html
        pip install .
        pip install --requirement requirements-dev.txt --upgrade --quiet
        python --version
        pip --version
        pip list
      shell: bash

    - name: Lint with flake8
      run: |
        flake8 . --count --show-source --statistics

    - name: Lint with mypy
      run: |
        # --install-types --non-interactive is only really necessary for Python 3.6
        mypy dgu --ignore-missing-imports --follow-imports=silent --show-column-numbers --install-types --non-interactive

    - name: Tests
      run: |
        coverage run --source dgu -m py.test dgu tests -v --junitxml=junit/test-results-${{ runner.os }}-${{ matrix.python-version }}.xml

    - name: Statistics
      if: success()
      run: |
        coverage report
